# Generated by Django 4.1 on 2022-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_consulta', models.CharField(max_length=50)),
                ('codigo_respuesta', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('consulta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_consulta', models.CharField(max_length=50)),
                ('codigo_respuesta', models.CharField(max_length=50)),
                ('abogado', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=50)),
            ],
        ),
    ]
